# AAAI ICWSM 2024 | Tutorial | June 3rd | 2-6pm
## <u>Collectivist and Perspectivist Approaches to Studying Online Toxicity</u>
### Yotam Shmargad, School of Government & Public Policy, University of Arizona

#### This is the <b>second</b> of two notebooks we will discuss during the tutorial. The notebook is written in Python and walks participants through analyzing YouTube comments from a *Perspectivist* approach. The notebook:
1.   Collects YouTube videos for <b>two</b> separate queries
2.   Collects comments AND replies for videos from each query and organizes data into comment-reply pairs
3.   Analyzes *hatefulness* in the two sets of comments and replies
4.   Compares the two sets in how hate in comments *(descriptive norm)* is associated with hate in replies
5.   Compares the two sets in how hate *(descriptive norm)* and like counts *(injunctive norm)* of comments <b>interact</b> in their association with hate in replies (i.e., Theory of Normative Social Behavior)

### 1. Collect YouTube videos for <b>two</b> separate queries`

In [1]:
# Install library for YouTube data collection https://youtube-data-api.readthedocs.io/en/latest/youtube_api.html
!pip install youtube-data-api

Collecting youtube-data-api
  Downloading youtube_data_api-0.0.21-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from youtube-data-api) (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from youtube-data-api) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->youtube-data-api) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->youtube-data-api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->youtube-data-api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->youtube-data-api) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-data-api) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-data-api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-data-api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-data-api) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->youtube-data-api) (1.17.0)
Downloading youtube_data_api-0.0.21-py3-none-any.whl (12 kB)
Installing collected packages: youtube-data-api
Successfully installed youtube-data-api-0.0.21

In [2]:
# Import libraries for data collection, management, and analysis
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from youtube_api import YouTubeDataAPI
import statsmodels.api as sm

In [3]:
# Obtain API Key from https://console.cloud.google.com/apis/
# Authenticate with YouTube - place the API Key you obtained between the quotes
yt = YouTubeDataAPI("AIzaSyAVo4MveZjFV8O7-cYczq5dHS-Est2qJww")

In [4]:
# Collect 100 videos using a query search - place your search term between the quotes
vids1 = yt.search("trump",max_results = 50)

In [5]:
# Collect 100 videos using a different query
vids2 = yt.search("biden",max_results = 50)

In [6]:
# Print number of videos collected for each query
print("Query 1:",len(vids1))
print("Query 2:",len(vids2))

Query 1: 50
Query 2: 50

### 2. Collect comments AND replies for videos from each query and organize data into comment-reply pairs

In [8]:
# Retrieve 500 comments for the ith video from second query
com = yt.get_video_comments(vids2[0]['video_id'],get_replies = True,max_results = 500)

In [9]:
# Place comment data into a pandas table
com_df = pd.DataFrame(com)

In [10]:
# Print columns that have a period (.) in the comment_id, which indicates a reply
com_df[com_df['comment_id'].str.contains('.', regex=False)]

,video_id,commenter_channel_url,commenter_channel_id,commenter_channel_display_name,comment_id,comment_like_count,comment_publish_date,text,commenter_rating,comment_parent_id,collection_date,reply_count
96,None,http://www.youtube.com/@DV_51,UCi7jriYZGYJoCLhA09b8kMw,@DV_51,UgytCUKu28TxwJZpw814AaABAg.AVdsYJ3dklfAVdymD5ybl4,0,1.776314e+09,Cope.,none,UgytCUKu28TxwJZpw814AaABAg,2026-04-16 16:20:06.006312,NaN
97,None,http://www.youtube.com/@DavidLStone-qy8xh,UC-WXj5co89gywZMIdOgLu-Q,@DavidLStone-qy8xh,UgxipKY4ytIoEDaZ8Uh4AaABAg.AVd_VeO6BiKAVdr3Xh6ESt,1,1.776310e+09,He called him Barack three times!,none,UgxipKY4ytIoEDaZ8Uh4AaABAg,2026-04-16 16:20:06.091430,NaN
98,None,http://www.youtube.com/@Mingus1456,UCJmGPajrBPWHtd2527fFoDA,@Mingus1456,UgxugNbc6vWX2WQX1DN4AaABAg.AVcyPJ9TuboAVda2-ivAHm,0,1.776301e+09,Have you listened to Donny lately . Trump does...,none,UgxugNbc6vWX2WQX1DN4AaABAg,2026-04-16 16:20:06.176464,NaN
99,None,http://www.youtube.com/@TonyHobbies,UCM2t09FL7NWNnI0te3jWWXg,@TonyHobbies,UgxugNbc6vWX2WQX1DN4AaABAg.AVcyPJ9TuboAVdm6kGBWq3,0,1.776307e+09,For what campaign? the guy isn’t running again...,none,UgxugNbc6vWX2WQX1DN4AaABAg,2026-04-16 16:20:06.176516,NaN
100,None,http://www.youtube.com/@Mingus1456,UCJmGPajrBPWHtd2527fFoDA,@Mingus1456,UgxV9l1daF3CISA32rt4AaABAg.AVcuTfRyUWsAVdaI_iO0tt,0,1.776301e+09,Cause that bible salesman is a narcissist a li...,none,UgxV9l1daF3CISA32rt4AaABAg,2026-04-16 16:20:06.296299,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
171,None,http://www.youtube.com/@mariaashley87,UCxb7OPlgFxPQF1qj23iL5Uw,@mariaashley87,UgwHZ6gyLF_F_wBVOxF4AaABAg.AVcfMKM_fw3AVctYVehuSn,0,1.776277e+09,​@wildbill9681No he doesn't,none,UgwHZ6gyLF_F_wBVOxF4AaABAg,2026-04-16 16:20:08.005660,NaN
172,None,http://www.youtube.com/@anniegoulaheee8025,UCC5AiMD0Huaqk7pYxqKguxA,@anniegoulaheee8025,UgxqSaBEJnu_r8FSEt54AaABAg.AVcfHl3iFQ_AVchdHvmD2m,2,1.776271e+09,"""But! The Dow!""~ Pam Bondi\n\n""Lookit my pen!""...",none,UgxqSaBEJnu_r8FSEt54AaABAg,2026-04-16 16:20:08.107090,NaN
173,None,http://www.youtube.com/@mariaashley87,UCxb7OPlgFxPQF1qj23iL5Uw,@mariaashley87,UgxqSaBEJnu_r8FSEt54AaABAg.AVcfHl3iFQ_AVctP3FtPte,3,1.776277e+09,​@anniegoulaheee8025That was Biden 😂😂😂,none,UgxqSaBEJnu_r8FSEt54AaABAg,2026-04-16 16:20:08.107132,NaN
174,None,http://www.youtube.com/@DEKKD,UCLb5Bo8pQGnhDtx4aWCFLaA,@DEKKD,UgxqSaBEJnu_r8FSEt54AaABAg.AVcfHl3iFQ_AVd_3T5xlVm,0,1.776300e+09,@anniegoulaheee8025. Another one of you racist...,none,UgxqSaBEJnu_r8FSEt54AaABAg,2026-04-16 16:20:08.107158,NaN
175,None,http://www.youtube.com/@Mingus1456,UCJmGPajrBPWHtd2527fFoDA,@Mingus1456,UgxqSaBEJnu_r8FSEt54AaABAg.AVcfHl3iFQ_AVd_cMjOBwV,0,1.776301e+09,Trump is the stupidity. Have you seen him in h...,none,UgxqSaBEJnu_r8FSEt54AaABAg,2026-04-16 16:20:08.107183,NaN

In [11]:
# Subset comments to two different dataframes: 1) popular comments and 2) replies
pop_df = com_df[com_df['reply_count'] > 0]
rep_df = com_df[com_df['comment_parent_id'].isnull()==False]

In [12]:
# Print dimensions of comment df, popular comment df, and reply df
print("All comments:",com_df.shape)
print("Popular comments:",pop_df.shape)
print("Replies:",rep_df.shape)

All comments: (176, 12)
Popular comments: (24, 12)
Replies: (80, 12)

In [13]:
# Extract relevant columns from new dataframes
small_pop_df = pop_df[['video_id','comment_id','comment_like_count','text']]
small_rep_df = rep_df[['video_id','comment_parent_id','comment_like_count','text']]

In [14]:
# Merge the two dataframes so that data about comments and their replies are in the same row
mer_df = pd.merge(small_pop_df,small_rep_df,left_on='comment_id', right_on='comment_parent_id', how='inner', suffixes=('_com', '_rep'))

In [16]:
# Print merged dataframe
mer_df

,video_id_com,comment_id,comment_like_count_com,text_com,video_id_rep,comment_parent_id,comment_like_count_rep,text_rep
0,6bN_YI-3phA,UgytCUKu28TxwJZpw814AaABAg,0,"Notice he calls him the right name though, Tru...",None,UgytCUKu28TxwJZpw814AaABAg,0,Cope.
1,6bN_YI-3phA,UgxipKY4ytIoEDaZ8Uh4AaABAg,2,Biden did not call him Obama he just think thi...,None,UgxipKY4ytIoEDaZ8Uh4AaABAg,1,He called him Barack three times!
2,6bN_YI-3phA,UgxugNbc6vWX2WQX1DN4AaABAg,1,This is embarrassing and definitely should be ...,None,UgxugNbc6vWX2WQX1DN4AaABAg,0,Have you listened to Donny lately . Trump does...
3,6bN_YI-3phA,UgxugNbc6vWX2WQX1DN4AaABAg,1,This is embarrassing and definitely should be ...,None,UgxugNbc6vWX2WQX1DN4AaABAg,0,For what campaign? the guy isn’t running again...
4,6bN_YI-3phA,UgxV9l1daF3CISA32rt4AaABAg,5,That's as funny as a Bible salesman not knowin...,None,UgxV9l1daF3CISA32rt4AaABAg,0,Cause that bible salesman is a narcissist a li...
...,...,...,...,...,...,...,...,...
75,6bN_YI-3phA,UgwHZ6gyLF_F_wBVOxF4AaABAg,39,"🤷🏾‍♂️ you know, Democrats think we all look al...",None,UgwHZ6gyLF_F_wBVOxF4AaABAg,0,​@wildbill9681No he doesn't
76,6bN_YI-3phA,UgxqSaBEJnu_r8FSEt54AaABAg,38,Stupid is as stupid does,None,UgxqSaBEJnu_r8FSEt54AaABAg,2,"""But! The Dow!""~ Pam Bondi\n\n""Lookit my pen!""..."
77,6bN_YI-3phA,UgxqSaBEJnu_r8FSEt54AaABAg,38,Stupid is as stupid does,None,UgxqSaBEJnu_r8FSEt54AaABAg,3,​@anniegoulaheee8025That was Biden 😂😂😂
78,6bN_YI-3phA,UgxqSaBEJnu_r8FSEt54AaABAg,38,Stupid is as stupid does,None,UgxqSaBEJnu_r8FSEt54AaABAg,0,@anniegoulaheee8025. Another one of you racist...
79,6bN_YI-3phA,UgxqSaBEJnu_r8FSEt54AaABAg,38,Stupid is as stupid does,None,UgxqSaBEJnu_r8FSEt54AaABAg,0,Trump is the stupidity. Have you seen him in h...

In [17]:
# Print dimensions of merged dataframe
mer_df.shape

(80, 8)

In [ ]:
# Define empty table for storing comment-reply pairs from videos in first query
comreps1 = pd.DataFrame(columns=['video_id_com','comment_id','comment_like_count_com', 'text_com','video_id_rep','comment_parent_id','comment_like_count_rep','text_rep'])

In [24]:
comreps1

Empty DataFrame
Columns: [video_id_com, comment_id, comment_like_count_com, text_com, video_id_rep, comment_parent_id, comment_like_count_rep, text_rep]
Index: []

In [25]:
# Iterate through videos from first query, pull 500 comments per video, organize into comment-reply pairs, and append them to a single table
for i in vids1:
  try:
    c = yt.get_video_comments(i['video_id'],get_replies = True,max_results = 300)
    cdf = pd.DataFrame(c)
    pdf = cdf[cdf['reply_count'] > 0]
    rdf = cdf[cdf['comment_parent_id'].isnull()==False]
    spdf = pdf[['video_id','comment_id','comment_like_count','text']]
    srdf = rdf[['video_id','comment_parent_id','comment_like_count','text']]
    mdf = pd.merge(spdf,srdf,left_on='comment_id', right_on='comment_parent_id', how='inner', suffixes=('_com', '_rep'))
    comreps1 = pd.concat([comreps1,mdf],ignore_index=True)
    print(i['video_id'],'success!',mdf.shape[0])
  except:
    print(i['video_id'],'fail')

LJDhSYAVeZ8 success! 0
gzSaKhEtiTA success! 0
tMiZpH3ncEA success! 0
IECT1tm6okE success! 0
EPqPLWMLMJ0 success! 0
rPE5ZUOfpfI success! 0
qOse2LGQ3dc success! 92
YdXMksgj2s8 fail
_7dMrX-YY34 success! 2
nZOxZKDAJH0 success! 33
RdcrD5cm7LE success! 0
OzVvjgeOJwc success! 44
wgW_JNkt_Xk success! 0
TRlqBkALgac success! 26
Audx8lMTLhE success! 16
vIXa03UuXFY success! 1
JbxH8fPAlw4 success! 18
2OvkG99bw04 success! 44
YE_-pdnNTT4 success! 89
MPaH0BillqM success! 2
QyoFsWc_zyU success! 0
SRbC3-U6FFo fail
MAm-iDAYQbs success! 16
nEfJVa5TdjU success! 49
e8c9K6wB71g success! 0
uaNeK-gpJZo success! 58
sGlPwHyXGhc success! 0
pAQ1yLxt4-s success! 0
h3U9FB40tCE success! 0
xcwcnb2ckO0 success! 0
us77yDvCclc success! 0
z0tuhnncWL0 success! 39
lYoTpc3w6UA success! 100
jkhEmDbiWXw success! 0
htKz_MtUJPo fail
F2Naz4sWO68 success! 0
cA26AU16bXs success! 0
Z0LuknYnItg success! 152
-X0rztrtcjA success! 0
s6Q6qH_dccc success! 0
sCyf5x4p2nE fail
G5BqX7aBlxo success! 0
HooaVIDYUeU success! 0
r9F6haZLYYA success! 0
bbski5u9A34 success! 0
XZSWWlDgl30 success! 30
A91zSjQJUp8 success! 204
a4EYZjzC5DI success! 0
zRRbALCbcDA success! 0
CUYZo8IGyqk success! 0

In [27]:
# Print dimensions of comment-reply table for first query
comreps1.shape

(1015, 8)

In [28]:
# Define empty table for storing comment-reply pairs from videos in second query
comreps2 = pd.DataFrame(columns=['video_id_com','comment_id','comment_like_count_com', 'text_com','video_id_rep','comment_parent_id','comment_like_count_rep','text_rep'])

In [ ]:
# Iterate through videos from second query, pull 500 comments per video, organize into comment-reply pairs, and append them to a single table
for i in vids2:
  try:
    c = yt.get_video_comments(i['video_id'],get_replies = True,max_results = 400)
    cdf = pd.DataFrame(c)
    pdf = cdf[cdf['reply_count'] > 0]
    rdf = cdf[cdf['comment_parent_id'].isnull()==False]
    spdf = pdf[['video_id','comment_id','comment_like_count','text']]
    srdf = rdf[['video_id','comment_parent_id','comment_like_count','text']]
    mdf = pd.merge(spdf,srdf,left_on='comment_id', right_on='comment_parent_id', how='inner', suffixes=('_com', '_rep'))
    comreps2 = pd.concat([comreps2,mdf],ignore_index=True)
    print(i['video_id'],'success!',mdf.shape[0])
  except:
    print(i['video_id'],'fail')

6bN_YI-3phA success! 80
zA25aFMaWHo success! 50
7jzqgWjgbyM success! 7
W9cM8URS8sM success! 0
xQ1joMHlGB0 success! 9
q80Lvv_K93g fail
k3uPDZfL_Cs success! 5
_M98wS0Sl9Q success! 1
Bx9q0fFZPI8 success! 105
XpPDifR_ox0 success! 25
IQ764Ouy6-c fail
TZ8NjDwNXhQ success! 96
yemJao8vsks success! 0
3kGRDbWGtoU fail
abe1ILEQ81A success! 212
6vM08vSHkW8 fail
7fTrdlvO4ag success! 7
zyaFfwO1YqE success! 0
n2oGwPePsxk success! 66
cavgHDz6y5Q success! 4
MRKJwAEXZj8 success! 177
Q54hyn8AiCk success! 7
GWhh_zIwsQE fail
sZFFeyce2Yg success! 0
n5AXo9SEJtA fail
xNd_60EY2gA success! 0
HZPrkgFYS7M success! 0
30NJKzfGd6A success! 4
JCjxbEDkzUw success! 11
AVPuMK7MTeA success! 4
ks_Is8rALrk success! 25
OmYzVqa_Tro success! 77
q9qElTSSblE success! 8
G6Uqkj1fyR0 success! 36
euIY6eFL4Qs success! 124
VeCuFOeJDyk success! 11
XTPIy2u2x2w success! 0
bC9w-4KUSJs success! 1
ZpF0OIMzvPM fail
-y4f9H8AnFc success! 212
y6wjp4UbPYo success! 0

In [ ]:
# Print dimensions of comment-reply table for second query
comreps2.shape

### 3. Analyze *hatefulness* in the two sets of comments and replies

In [ ]:
# Install library for hatefulness analysis https://github.com/pysentimiento/pysentimiento
!pip install pysentimiento

In [ ]:
# Import library for text analysis
from pysentimiento import create_analyzer

In [ ]:
# Load hatefulness analyzer in English
hate = create_analyzer(task="hate_speech",lang="en")

In [ ]:
# Create empty columns to store probabilities of hate for all comments and replies
comreps1['hate_com'] = ''
comreps1['hate_rep'] = ''
comreps2['hate_com'] = ''
comreps2['hate_rep'] = ''

In [ ]:
# Print table of comment-reply pairs from first query with added column
comreps1

In [ ]:
# Initialize object to store comment_id of previous comment in first query
lastcom1 = 'abcdefg'

In [ ]:
# Iterate through comments and replies of first query, analyze for hatefulness, then place scores in the table
# NOTE: this may take several minutes to complete
for index,row in comreps1.iterrows():
  if(row['comment_id'] != lastcom1):
    h_com = hate.predict(row['text_com'])
    comreps1.at[index, 'hate_com'] = h_com.probas['hateful']
    lastcom1 = row['comment_id']
  else:
    comreps1.at[index, 'hate_com'] = h_com.probas['hateful']
  h_rep = hate.predict(row['text_rep'])
  comreps1.at[index, 'hate_rep'] = h_rep.probas['hateful']
  if((index + 1) % 50 == 0):
    print(index + 1,end=" ")

In [ ]:
# Print comments, replies, and hatefulness probabilities for first query
comreps1

In [ ]:
# Initialize object to store comment_id of previous comment in second query
lastcom2 = 'abcdefg'

In [ ]:
# Iterate through comments and replies of second query, analyze for hatefulness, then place scores in the table
# NOTE: this may take several minutes to complete
for index,row in comreps2.iterrows():
  if(row['comment_id'] != lastcom2):
    h_com = hate.predict(row['text_com'])
    comreps2.at[index, 'hate_com'] = h_com.probas['hateful']
    lastcom2 = row['comment_id']
  else:
    comreps2.at[index, 'hate_com'] = h_com.probas['hateful']
  h_rep = hate.predict(row['text_rep'])
  comreps2.at[index, 'hate_rep'] = h_rep.probas['hateful']
  if((index + 1) % 50 == 0):
    print(index + 1,end=" ")

In [ ]:
# Print comments, replies, and hatefulness probabilities for second query
comreps2

### 4. Compare the two sets in how hate in comments *(descriptive norm)* is associated with hate in replies

In [ ]:
# Create columns to store indicator for first/second query
comreps1['query'] = 0
comreps2['query'] = 1

In [ ]:
# Append the two tables together
all = pd.concat([comreps1,comreps2],ignore_index = True)

In [ ]:
# Print table of comments
all

In [ ]:
# Print variable types
all.dtypes

In [ ]:
# Convert variable types to numbers
all['comment_like_count_com'] = all['comment_like_count_com'].astype(int)
all['hate_com'] = all['hate_com'].astype(float)
all['comment_like_count_rep'] = all['comment_like_count_rep'].astype(int)
all['hate_rep'] = all['hate_rep'].astype(float)

In [ ]:
# Print variable types after changes
all.dtypes

In [ ]:
# Create binary variables capturing if probability of hatefulness in comments and replies > 50%
all['hate_thresh_com'] = all['hate_com'].apply(lambda x: 1 if x > .5 else 0)
all['hate_thresh_rep'] = all['hate_rep'].apply(lambda x: 1 if x > .5 else 0)

In [ ]:
# Print number of comment-reply pairs where comment has probability of hatefulness > 50%
all.loc[all['hate_thresh_com'] == 1].size

In [ ]:
# Print number of comment-reply pairs where reply has probability of hatefulness > 50%
all.loc[all['hate_thresh_rep'] == 1].size

In [ ]:
# Create column of all 1s to add a constant to the models
all['constant'] = 1

In [ ]:
# Model how comment hate probability is associated with reply hate probability using OLS regression
model1 = sm.OLS(all['hate_rep'],all[['hate_com','constant']])

In [ ]:
# Print Model 1 results
model1.fit().summary()

In [ ]:
# Model how comment hate prevalence is associated with reply hate prevalence using OLS regression
model2 = sm.OLS(all['hate_thresh_rep'],all[['hate_thresh_com','constant']])

In [ ]:
# Print Model 2 results
model2.fit().summary()

In [ ]:
# Model how comment hate prevalence is associated with reply hate prevalence using Logit regression
model3 = sm.GLM(all['hate_thresh_rep'],all[['hate_thresh_com','constant']],family=sm.families.Binomial())

In [ ]:
# Print Model 3 results
model3.fit().summary()

In [ ]:
# Create columns capturing the interaction between query and hatefulness of comments
all['interaction'] = all['query']*all['hate_com']
all['int_thresh'] = all['query']*all['hate_thresh_com']

In [ ]:
# Model how comment-reply hate probability association varies across the two queries using OLS regression
model4 = sm.OLS(all['hate_rep'],all[['hate_com','query','interaction','constant']])

In [ ]:
# Print Model 4 results
model4.fit().summary()

In [ ]:
# Model how comment-reply hate prevalence association varies across the two queries using Logit regression
model5 = sm.GLM(all['hate_thresh_rep'],all[['hate_thresh_com','query','int_thresh','constant']],family=sm.families.Binomial())

In [ ]:
# Print Model 5 results
model5.fit().summary()

### 5. Compare the two sets in how hate *(descriptive norm)* and like counts *(injunctive norm)* of comments <b>interact</b> in their association with hate in replies (i.e., Theory of Normative Social Behavior)

In [ ]:
# Create columns capturing the interaction between like counts and hatefulness of comments
all['tnsb'] = all['comment_like_count_com']*all['hate_com']
all['tnsb_thresh'] = all['comment_like_count_com']*all['hate_thresh_com']

In [ ]:
# Model how comment-reply hate probability association varies with like counts using OLS regression
model6 = sm.OLS(all['hate_rep'],all[['hate_com','comment_like_count_com','tnsb','constant']])

In [ ]:
# Print Model 6 results
model6.fit().summary()

In [ ]:
# Model how comment-reply hate prevalence association varies with like counts using Logit regression
model7 = sm.GLM(all['hate_thresh_rep'],all[['hate_thresh_com','comment_like_count_com','tnsb_thresh','constant']],family=sm.families.Binomial())

In [ ]:
# Print Model 7 results
model7.fit().summary()

In [ ]:
# Create column capturing the interaction between query and like counts of comments
all['q_like'] = all['comment_like_count_com']*all['query']

In [ ]:
# Create columns capturing the TRIPLE interaction between query, like counts, and hatefulness of comments
all['tnsb_int'] = all['comment_like_count_com']*all['hate_com']*all['query']
all['tnsb_int_thresh'] = all['comment_like_count_com']*all['hate_thresh_com']*all['query']

In [ ]:
# Model how comment-reply hate probability association varies with like counts AND query using OLS regression
model8 = sm.OLS(all['hate_rep'],all[['hate_com','comment_like_count_com','query','tnsb','interaction','q_like','tnsb_int','constant']])

In [ ]:
# Print Model 8 results
model8.fit().summary()

In [ ]:
# Model how comment-reply hate prevalence association varies with like counts AND query using Logit regression
model9 = sm.GLM(all['hate_thresh_rep'],all[['hate_thresh_com','comment_like_count_com','query','tnsb_thresh','int_thresh','q_like','tnsb_int_thresh','constant']],family=sm.families.Binomial())

In [ ]:
# Print Model 9 results
model9.fit().summary()

#### <u>Additional considerations</u>
1.   Comment like counts are skewed --> could transform with logarithm
2.   Arbitrary threshold of .5 for hate --> higher numbers (e.g., .6, .9) are sometimes used<br> --> likely need more data
3.   Add fixed/random effects for video, comment, and/or authors<br>--> likely need more data