# AAAI ICWSM 2024 | Tutorial | June 3rd | 2-6pm
## <u>Collectivist and Perspectivist Approaches to Studying Online Toxicity</u>
### Yotam Shmargad, School of Government & Public Policy, University of Arizona

#### This is the <b>second</b> of two notebooks we will discuss during the tutorial. The notebook is written in Python and walks participants through analyzing YouTube comments from a *Perspectivist* approach. The notebook:
1.   Collects YouTube videos for <b>two</b> separate queries
2.   Collects comments AND replies for videos from each query and organizes data into comment-reply pairs
3.   Analyzes *hatefulness* in the two sets of comments and replies
4.   Compares the two sets in how hate in comments *(descriptive norm)* is associated with hate in replies
5.   Compares the two sets in how hate *(descriptive norm)* and like counts *(injunctive norm)* of comments <b>interact</b> in their association with hate in replies (i.e., Theory of Normative Social Behavior)

### 1. Collect YouTube videos for <b>two</b> separate queries`

In [1]:
# Install library for YouTube data collection https://youtube-data-api.readthedocs.io/en/latest/youtube_api.html
!pip install youtube-data-api

Collecting youtube-data-api
  Downloading youtube_data_api-0.0.21-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from youtube-data-api) (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from youtube-data-api) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->youtube-data-api) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->youtube-data-api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->youtube-data-api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->youtube-data-api) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-data-api) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-data-api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-data-api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-data-api) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->youtube-data-api) (1.17.0)
Downloading youtube_data_api-0.0.21-py3-none-any.whl (12 kB)
Installing collected packages: youtube-data-api
Successfully installed youtube-data-api-0.0.21

In [2]:
# Import libraries for data collection, management, and analysis
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from youtube_api import YouTubeDataAPI
import statsmodels.api as sm

In [3]:
# Obtain API Key from https://console.cloud.google.com/apis/
# Authenticate with YouTube - place the API Key you obtained between the quotes
yt = YouTubeDataAPI("AIzaSyAVo4MveZjFV8O7-cYczq5dHS-Est2qJww")

In [4]:
# Collect 100 videos using a query search - place your search term between the quotes
vids1 = yt.search("trump",max_results = 50)

In [5]:
# Collect 100 videos using a different query
vids2 = yt.search("biden",max_results = 50)

In [6]:
# Print number of videos collected for each query
print("Query 1:",len(vids1))
print("Query 2:",len(vids2))

Query 1: 50
Query 2: 50

### 2. Collect comments AND replies for videos from each query and organize data into comment-reply pairs

In [8]:
# Retrieve 500 comments for the ith video from second query
com = yt.get_video_comments(vids2[0]['video_id'],get_replies = True,max_results = 500)

In [9]:
# Place comment data into a pandas table
com_df = pd.DataFrame(com)

In [10]:
# Print columns that have a period (.) in the comment_id, which indicates a reply
com_df[com_df['comment_id'].str.contains('.', regex=False)]

,video_id,commenter_channel_url,commenter_channel_id,commenter_channel_display_name,comment_id,comment_like_count,comment_publish_date,text,commenter_rating,comment_parent_id,collection_date,reply_count
96,None,http://www.youtube.com/@DV_51,UCi7jriYZGYJoCLhA09b8kMw,@DV_51,UgytCUKu28TxwJZpw814AaABAg.AVdsYJ3dklfAVdymD5ybl4,0,1.776314e+09,Cope.,none,UgytCUKu28TxwJZpw814AaABAg,2026-04-16 16:20:06.006312,NaN
97,None,http://www.youtube.com/@DavidLStone-qy8xh,UC-WXj5co89gywZMIdOgLu-Q,@DavidLStone-qy8xh,UgxipKY4ytIoEDaZ8Uh4AaABAg.AVd_VeO6BiKAVdr3Xh6ESt,1,1.776310e+09,He called him Barack three times!,none,UgxipKY4ytIoEDaZ8Uh4AaABAg,2026-04-16 16:20:06.091430,NaN
98,None,http://www.youtube.com/@Mingus1456,UCJmGPajrBPWHtd2527fFoDA,@Mingus1456,UgxugNbc6vWX2WQX1DN4AaABAg.AVcyPJ9TuboAVda2-ivAHm,0,1.776301e+09,Have you listened to Donny lately . Trump does...,none,UgxugNbc6vWX2WQX1DN4AaABAg,2026-04-16 16:20:06.176464,NaN
99,None,http://www.youtube.com/@TonyHobbies,UCM2t09FL7NWNnI0te3jWWXg,@TonyHobbies,UgxugNbc6vWX2WQX1DN4AaABAg.AVcyPJ9TuboAVdm6kGBWq3,0,1.776307e+09,For what campaign? the guy isn’t running again...,none,UgxugNbc6vWX2WQX1DN4AaABAg,2026-04-16 16:20:06.176516,NaN
100,None,http://www.youtube.com/@Mingus1456,UCJmGPajrBPWHtd2527fFoDA,@Mingus1456,UgxV9l1daF3CISA32rt4AaABAg.AVcuTfRyUWsAVdaI_iO0tt,0,1.776301e+09,Cause that bible salesman is a narcissist a li...,none,UgxV9l1daF3CISA32rt4AaABAg,2026-04-16 16:20:06.296299,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
171,None,http://www.youtube.com/@mariaashley87,UCxb7OPlgFxPQF1qj23iL5Uw,@mariaashley87,UgwHZ6gyLF_F_wBVOxF4AaABAg.AVcfMKM_fw3AVctYVehuSn,0,1.776277e+09,​@wildbill9681No he doesn't,none,UgwHZ6gyLF_F_wBVOxF4AaABAg,2026-04-16 16:20:08.005660,NaN
172,None,http://www.youtube.com/@anniegoulaheee8025,UCC5AiMD0Huaqk7pYxqKguxA,@anniegoulaheee8025,UgxqSaBEJnu_r8FSEt54AaABAg.AVcfHl3iFQ_AVchdHvmD2m,2,1.776271e+09,"""But! The Dow!""~ Pam Bondi\n\n""Lookit my pen!""...",none,UgxqSaBEJnu_r8FSEt54AaABAg,2026-04-16 16:20:08.107090,NaN
173,None,http://www.youtube.com/@mariaashley87,UCxb7OPlgFxPQF1qj23iL5Uw,@mariaashley87,UgxqSaBEJnu_r8FSEt54AaABAg.AVcfHl3iFQ_AVctP3FtPte,3,1.776277e+09,​@anniegoulaheee8025That was Biden 😂😂😂,none,UgxqSaBEJnu_r8FSEt54AaABAg,2026-04-16 16:20:08.107132,NaN
174,None,http://www.youtube.com/@DEKKD,UCLb5Bo8pQGnhDtx4aWCFLaA,@DEKKD,UgxqSaBEJnu_r8FSEt54AaABAg.AVcfHl3iFQ_AVd_3T5xlVm,0,1.776300e+09,@anniegoulaheee8025. Another one of you racist...,none,UgxqSaBEJnu_r8FSEt54AaABAg,2026-04-16 16:20:08.107158,NaN
175,None,http://www.youtube.com/@Mingus1456,UCJmGPajrBPWHtd2527fFoDA,@Mingus1456,UgxqSaBEJnu_r8FSEt54AaABAg.AVcfHl3iFQ_AVd_cMjOBwV,0,1.776301e+09,Trump is the stupidity. Have you seen him in h...,none,UgxqSaBEJnu_r8FSEt54AaABAg,2026-04-16 16:20:08.107183,NaN

In [11]:
# Subset comments to two different dataframes: 1) popular comments and 2) replies
pop_df = com_df[com_df['reply_count'] > 0]
rep_df = com_df[com_df['comment_parent_id'].isnull()==False]

In [12]:
# Print dimensions of comment df, popular comment df, and reply df
print("All comments:",com_df.shape)
print("Popular comments:",pop_df.shape)
print("Replies:",rep_df.shape)

All comments: (176, 12)
Popular comments: (24, 12)
Replies: (80, 12)

In [13]:
# Extract relevant columns from new dataframes
small_pop_df = pop_df[['video_id','comment_id','comment_like_count','text']]
small_rep_df = rep_df[['video_id','comment_parent_id','comment_like_count','text']]

In [14]:
# Merge the two dataframes so that data about comments and their replies are in the same row
mer_df = pd.merge(small_pop_df,small_rep_df,left_on='comment_id', right_on='comment_parent_id', how='inner', suffixes=('_com', '_rep'))

In [16]:
# Print merged dataframe
mer_df

,video_id_com,comment_id,comment_like_count_com,text_com,video_id_rep,comment_parent_id,comment_like_count_rep,text_rep
0,6bN_YI-3phA,UgytCUKu28TxwJZpw814AaABAg,0,"Notice he calls him the right name though, Tru...",None,UgytCUKu28TxwJZpw814AaABAg,0,Cope.
1,6bN_YI-3phA,UgxipKY4ytIoEDaZ8Uh4AaABAg,2,Biden did not call him Obama he just think thi...,None,UgxipKY4ytIoEDaZ8Uh4AaABAg,1,He called him Barack three times!
2,6bN_YI-3phA,UgxugNbc6vWX2WQX1DN4AaABAg,1,This is embarrassing and definitely should be ...,None,UgxugNbc6vWX2WQX1DN4AaABAg,0,Have you listened to Donny lately . Trump does...
3,6bN_YI-3phA,UgxugNbc6vWX2WQX1DN4AaABAg,1,This is embarrassing and definitely should be ...,None,UgxugNbc6vWX2WQX1DN4AaABAg,0,For what campaign? the guy isn’t running again...
4,6bN_YI-3phA,UgxV9l1daF3CISA32rt4AaABAg,5,That's as funny as a Bible salesman not knowin...,None,UgxV9l1daF3CISA32rt4AaABAg,0,Cause that bible salesman is a narcissist a li...
...,...,...,...,...,...,...,...,...
75,6bN_YI-3phA,UgwHZ6gyLF_F_wBVOxF4AaABAg,39,"🤷🏾‍♂️ you know, Democrats think we all look al...",None,UgwHZ6gyLF_F_wBVOxF4AaABAg,0,​@wildbill9681No he doesn't
76,6bN_YI-3phA,UgxqSaBEJnu_r8FSEt54AaABAg,38,Stupid is as stupid does,None,UgxqSaBEJnu_r8FSEt54AaABAg,2,"""But! The Dow!""~ Pam Bondi\n\n""Lookit my pen!""..."
77,6bN_YI-3phA,UgxqSaBEJnu_r8FSEt54AaABAg,38,Stupid is as stupid does,None,UgxqSaBEJnu_r8FSEt54AaABAg,3,​@anniegoulaheee8025That was Biden 😂😂😂
78,6bN_YI-3phA,UgxqSaBEJnu_r8FSEt54AaABAg,38,Stupid is as stupid does,None,UgxqSaBEJnu_r8FSEt54AaABAg,0,@anniegoulaheee8025. Another one of you racist...
79,6bN_YI-3phA,UgxqSaBEJnu_r8FSEt54AaABAg,38,Stupid is as stupid does,None,UgxqSaBEJnu_r8FSEt54AaABAg,0,Trump is the stupidity. Have you seen him in h...

In [17]:
# Print dimensions of merged dataframe
mer_df.shape

(80, 8)

In [30]:
# Define empty table for storing comment-reply pairs from videos in first query
comreps1 = pd.DataFrame(columns=['video_id_com','comment_id','comment_like_count_com', 'text_com','video_id_rep','comment_parent_id','comment_like_count_rep','text_rep'])

In [31]:
comreps1

Empty DataFrame
Columns: [video_id_com, comment_id, comment_like_count_com, text_com, video_id_rep, comment_parent_id, comment_like_count_rep, text_rep]
Index: []

In [32]:
# Iterate through videos from first query, pull 500 comments per video, organize into comment-reply pairs, and append them to a single table
for i in vids1:
  try:
    c = yt.get_video_comments(i['video_id'],get_replies = True,max_results = 300)
    cdf = pd.DataFrame(c)
    pdf = cdf[cdf['reply_count'] > 0]
    rdf = cdf[cdf['comment_parent_id'].isnull()==False]
    spdf = pdf[['video_id','comment_id','comment_like_count','text']]
    srdf = rdf[['video_id','comment_parent_id','comment_like_count','text']]
    mdf = pd.merge(spdf,srdf,left_on='comment_id', right_on='comment_parent_id', how='inner', suffixes=('_com', '_rep'))
    comreps1 = pd.concat([comreps1,mdf],ignore_index=True)
    print(i['video_id'],'success!',mdf.shape[0])
  except:
    print(i['video_id'],'fail')

LJDhSYAVeZ8 success! 0
gzSaKhEtiTA success! 0
tMiZpH3ncEA success! 0
IECT1tm6okE success! 0
EPqPLWMLMJ0 success! 0
rPE5ZUOfpfI success! 0
qOse2LGQ3dc success! 0
YdXMksgj2s8 fail
_7dMrX-YY34 success! 2
nZOxZKDAJH0 success! 33
RdcrD5cm7LE success! 0
OzVvjgeOJwc success! 0
wgW_JNkt_Xk success! 0
TRlqBkALgac success! 0
Audx8lMTLhE success! 16
vIXa03UuXFY success! 1
JbxH8fPAlw4 success! 0
2OvkG99bw04 success! 44
YE_-pdnNTT4 success! 31
MPaH0BillqM success! 2
QyoFsWc_zyU success! 0
SRbC3-U6FFo fail
MAm-iDAYQbs success! 16
nEfJVa5TdjU success! 49
e8c9K6wB71g success! 0
uaNeK-gpJZo success! 58
sGlPwHyXGhc success! 0
pAQ1yLxt4-s success! 0
h3U9FB40tCE success! 0
xcwcnb2ckO0 success! 0
us77yDvCclc success! 0
z0tuhnncWL0 success! 39
lYoTpc3w6UA success! 0
jkhEmDbiWXw success! 0
htKz_MtUJPo fail
F2Naz4sWO68 success! 0
cA26AU16bXs success! 0
Z0LuknYnItg success! 0
-X0rztrtcjA success! 0
s6Q6qH_dccc success! 0
sCyf5x4p2nE fail
G5BqX7aBlxo success! 0
HooaVIDYUeU success! 0
r9F6haZLYYA success! 0
bbski5u9A34 success! 0
XZSWWlDgl30 success! 30
A91zSjQJUp8 success! 4
a4EYZjzC5DI success! 0
zRRbALCbcDA success! 0
CUYZo8IGyqk success! 0

In [33]:
# Print dimensions of comment-reply table for first query
comreps1.shape

(325, 8)

In [35]:
# Define empty table for storing comment-reply pairs from videos in second query
comreps2 = pd.DataFrame(columns=['video_id_com','comment_id','comment_like_count_com', 'text_com','video_id_rep','comment_parent_id','comment_like_count_rep','text_rep'])

In [36]:
# Iterate through videos from second query, pull 500 comments per video, organize into comment-reply pairs, and append them to a single table
for i in vids2:
  try:
    c = yt.get_video_comments(i['video_id'],get_replies = True,max_results = 300)
    cdf = pd.DataFrame(c)
    pdf = cdf[cdf['reply_count'] > 0]
    rdf = cdf[cdf['comment_parent_id'].isnull()==False]
    spdf = pdf[['video_id','comment_id','comment_like_count','text']]
    srdf = rdf[['video_id','comment_parent_id','comment_like_count','text']]
    mdf = pd.merge(spdf,srdf,left_on='comment_id', right_on='comment_parent_id', how='inner', suffixes=('_com', '_rep'))
    comreps2 = pd.concat([comreps2,mdf],ignore_index=True)
    print(i['video_id'],'success!',mdf.shape[0])
  except:
    print(i['video_id'],'fail')

6bN_YI-3phA success! 80
zA25aFMaWHo success! 51
7jzqgWjgbyM success! 7
W9cM8URS8sM success! 0
xQ1joMHlGB0 success! 9
q80Lvv_K93g fail
k3uPDZfL_Cs success! 5
_M98wS0Sl9Q success! 1
Bx9q0fFZPI8 success! 105
XpPDifR_ox0 success! 25
IQ764Ouy6-c fail
TZ8NjDwNXhQ success! 96
yemJao8vsks success! 0
3kGRDbWGtoU fail
abe1ILEQ81A success! 112
6vM08vSHkW8 fail
7fTrdlvO4ag success! 7
zyaFfwO1YqE success! 0
n2oGwPePsxk success! 66
cavgHDz6y5Q success! 4
MRKJwAEXZj8 success! 177
Q54hyn8AiCk success! 7
GWhh_zIwsQE fail
sZFFeyce2Yg success! 0
n5AXo9SEJtA fail
xNd_60EY2gA success! 0
HZPrkgFYS7M success! 0
30NJKzfGd6A success! 4
JCjxbEDkzUw success! 11
AVPuMK7MTeA success! 4
ks_Is8rALrk success! 25
OmYzVqa_Tro success! 77
q9qElTSSblE success! 8
G6Uqkj1fyR0 success! 36
euIY6eFL4Qs success! 124
VeCuFOeJDyk success! 11
XTPIy2u2x2w success! 0
bC9w-4KUSJs success! 1
ZpF0OIMzvPM fail
-y4f9H8AnFc success! 193
y6wjp4UbPYo success! 0
PwX2Rh3EmAs success! 0
zoKA49y0a3Y success! 20
ssRvJ5CxMHc success! 0
oMSlZCFM5B8 success! 145
5B9nxSQJJWs success! 9
6qa6eQb30UM success! 0
cgeXm0g2MX8 success! 0
MHYydOTheZM success! 0
ZVvvDKsUyXk success! 141

In [37]:
# Print dimensions of comment-reply table for second query
comreps2.shape

(1561, 8)

### 3. Analyze *hatefulness* in the two sets of comments and replies

In [38]:
# Install library for hatefulness analysis https://github.com/pysentimiento/pysentimiento
!pip install pysentimiento

Collecting pysentimiento
  Downloading pysentimiento-0.7.3-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: accelerate>=0.27.2 in /usr/local/lib/python3.12/dist-packages (from pysentimiento) (1.13.0)
Requirement already satisfied: datasets>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pysentimiento) (4.0.0)
Collecting emoji>=1.6.1 (from pysentimiento)
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: spacy>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from pysentimiento) (3.8.14)
Requirement already satisfied: torch!=2.0.1,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pysentimiento) (2.10.0+cpu)
Requirement already satisfied: transformers>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from pysentimiento) (5.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.27.2->pysentimiento) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.27.2->pysentimiento) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.27.2->pysentimiento) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.27.2->pysentimiento) (6.0.3)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.27.2->pysentimiento) (1.10.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.27.2->pysentimiento) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.10.1->pysentimiento) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (2025.3.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (0.24.1)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy>=3.5.0->pysentimiento) (75.2.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch!=2.0.1,>=2.0.0->pysentimiento) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch!=2.0.1,>=2.0.0->pysentimiento) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch!=2.0.1,>=2.0.0->pysentimiento) (3.6.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.13.0->pysentimiento) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.13.0->pysentimiento) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=4.13.0->pysentimiento) (0.24.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=0.27.2->pysentimiento) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=0.27.2->pysentimiento) (0.28.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.5.0->pysentimiento) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.5.0->pysentimiento) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.5.0->pysentimiento) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.10.1->pysentimiento) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.10.1->pysentimiento) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.10.1->pysentimiento) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.10.1->pysentimiento) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch!=2.0.1,>=2.0.0->pysentimiento) (1.3.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy>=3.5.0->pysentimiento) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy>=3.5.0->pysentimiento) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy>=3.5.0->pysentimiento) (7.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy>=3.5.0->pysentimiento) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.10.1->pysentimiento) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.10.1->pysentimiento) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.10.1->pysentimiento) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.10.1->pysentimiento) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=0.27.2->pysentimiento) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=0.27.2->pysentimiento) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=0.27.2->pysentimiento) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.10.1->pysentimiento) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy>=3.5.0->pysentimiento) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy>=3.5.0->pysentimiento) (0.1.2)
Downloading pysentimiento-0.7.3-py3-none-any.whl (39 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 13.6 MB/s eta 0:00:00
Installing collected packages: emoji, pysentimiento
Successfully installed emoji-2.15.0 pysentimiento-0.7.3

In [39]:
# Import library for text analysis
from pysentimiento import create_analyzer

In [40]:
# Load hatefulness analyzer in English
hate = create_analyzer(task="hate_speech",lang="en")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/980 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/338 [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

In [41]:
# Create empty columns to store probabilities of hate for all comments and replies
comreps1['hate_com'] = ''
comreps1['hate_rep'] = ''
comreps2['hate_com'] = ''
comreps2['hate_rep'] = ''

In [42]:
# Print table of comment-reply pairs from first query with added column
comreps1

,video_id_com,comment_id,comment_like_count_com,text_com,video_id_rep,comment_parent_id,comment_like_count_rep,text_rep,hate_com,hate_rep
0,_7dMrX-YY34,Ugzwy62qcq4su1TAyQx4AaABAg,1,And his fools believe it,None,Ugzwy62qcq4su1TAyQx4AaABAg,0,No actually trump is making 14 billion dollars...,,
1,_7dMrX-YY34,Ugzwy62qcq4su1TAyQx4AaABAg,1,And his fools believe it,None,Ugzwy62qcq4su1TAyQx4AaABAg,0,​@repulse_wkey4432 follow the money,,
2,nZOxZKDAJH0,UgwbijTvkEdcVSuDFip4AaABAg,2,"Dos frases que para ser felices,hay que elimin...",None,UgwbijTvkEdcVSuDFip4AaABAg,0,Palabras de sabios.,,
3,nZOxZKDAJH0,Ugx4kyn5yHhMbhgtyFJ4AaABAg,0,Osea Trump quiere q el papá le aplauda sus est...,None,Ugx4kyn5yHhMbhgtyFJ4AaABAg,0,"La paz viene de Cristo , y el mundo reclama p...",,
4,nZOxZKDAJH0,UgxefcfPgnsU0EtZDn14AaABAg,0,"Creeré en el Papa, cuando como Jesucristo, se ...",None,UgxefcfPgnsU0EtZDn14AaABAg,0,Cree en Cristo atravez del Papa el papá es un...,,
...,...,...,...,...,...,...,...,...,...,...
320,XZSWWlDgl30,UgxXVHW4-KBEWsTjSgB4AaABAg,4,Es porque el general lo sabía porque posibleme...,None,UgxXVHW4-KBEWsTjSgB4AaABAg,0,"Primero, eso era obvio para los expertos. Segu...",,
321,A91zSjQJUp8,UgzJVZkvAwq2HYNhv_d4AaABAg,0,Harvard? With a stupid f**king hair style like...,None,UgzJVZkvAwq2HYNhv_d4AaABAg,0,Harvard University is one of the most prestigi...,,
322,A91zSjQJUp8,UgzA5mig0NToQ2AHJ6Z4AaABAg,0,Idk SNL is hilarious when they make fun of him...,None,UgzA5mig0NToQ2AHJ6Z4AaABAg,0,its not funny AT ALL to the rest of the world....,,
323,A91zSjQJUp8,UgzSwQWFgirlfmnzYul4AaABAg,9,Don't mention him or his administration at all...,None,UgzSwQWFgirlfmnzYul4AaABAg,1,O ya,,
324,A91zSjQJUp8,Ugx2Wu1l_KtuFCZBa5d4AaABAg,0,Ronald Rump… is the epitome of the word Stupid!,None,Ugx2Wu1l_KtuFCZBa5d4AaABAg,0,Your mom is actually the embodiment of it🤪🤪🤪,,

In [43]:
# Initialize object to store comment_id of previous comment in first query
lastcom1 = 'abcdefg'

In [44]:
# Iterate through comments and replies of first query, analyze for hatefulness, then place scores in the table
# NOTE: this may take several minutes to complete
for index,row in comreps1.iterrows():
  if(row['comment_id'] != lastcom1):
    h_com = hate.predict(row['text_com'])
    comreps1.at[index, 'hate_com'] = h_com.probas['hateful']
    lastcom1 = row['comment_id']
  else:
    comreps1.at[index, 'hate_com'] = h_com.probas['hateful']
  h_rep = hate.predict(row['text_rep'])
  comreps1.at[index, 'hate_rep'] = h_rep.probas['hateful']
  if((index + 1) % 50 == 0):
    print(index + 1,end=" ")

50 100 150 200 250 300

In [45]:
# Print comments, replies, and hatefulness probabilities for first query
comreps1

,video_id_com,comment_id,comment_like_count_com,text_com,video_id_rep,comment_parent_id,comment_like_count_rep,text_rep,hate_com,hate_rep
0,_7dMrX-YY34,Ugzwy62qcq4su1TAyQx4AaABAg,1,And his fools believe it,None,Ugzwy62qcq4su1TAyQx4AaABAg,0,No actually trump is making 14 billion dollars...,0.029216,0.017533
1,_7dMrX-YY34,Ugzwy62qcq4su1TAyQx4AaABAg,1,And his fools believe it,None,Ugzwy62qcq4su1TAyQx4AaABAg,0,​@repulse_wkey4432 follow the money,0.029216,0.020233
2,nZOxZKDAJH0,UgwbijTvkEdcVSuDFip4AaABAg,2,"Dos frases que para ser felices,hay que elimin...",None,UgwbijTvkEdcVSuDFip4AaABAg,0,Palabras de sabios.,0.015486,0.018797
3,nZOxZKDAJH0,Ugx4kyn5yHhMbhgtyFJ4AaABAg,0,Osea Trump quiere q el papá le aplauda sus est...,None,Ugx4kyn5yHhMbhgtyFJ4AaABAg,0,"La paz viene de Cristo , y el mundo reclama p...",0.015134,0.015824
4,nZOxZKDAJH0,UgxefcfPgnsU0EtZDn14AaABAg,0,"Creeré en el Papa, cuando como Jesucristo, se ...",None,UgxefcfPgnsU0EtZDn14AaABAg,0,Cree en Cristo atravez del Papa el papá es un...,0.016532,0.015374
...,...,...,...,...,...,...,...,...,...,...
320,XZSWWlDgl30,UgxXVHW4-KBEWsTjSgB4AaABAg,4,Es porque el general lo sabía porque posibleme...,None,UgxXVHW4-KBEWsTjSgB4AaABAg,0,"Primero, eso era obvio para los expertos. Segu...",0.016047,0.015406
321,A91zSjQJUp8,UgzJVZkvAwq2HYNhv_d4AaABAg,0,Harvard? With a stupid f**king hair style like...,None,UgzJVZkvAwq2HYNhv_d4AaABAg,0,Harvard University is one of the most prestigi...,0.031682,0.016563
322,A91zSjQJUp8,UgzA5mig0NToQ2AHJ6Z4AaABAg,0,Idk SNL is hilarious when they make fun of him...,None,UgzA5mig0NToQ2AHJ6Z4AaABAg,0,its not funny AT ALL to the rest of the world....,0.017522,0.113063
323,A91zSjQJUp8,UgzSwQWFgirlfmnzYul4AaABAg,9,Don't mention him or his administration at all...,None,UgzSwQWFgirlfmnzYul4AaABAg,1,O ya,0.015079,0.044985
324,A91zSjQJUp8,Ugx2Wu1l_KtuFCZBa5d4AaABAg,0,Ronald Rump… is the epitome of the word Stupid!,None,Ugx2Wu1l_KtuFCZBa5d4AaABAg,0,Your mom is actually the embodiment of it🤪🤪🤪,0.019486,0.818246

In [46]:
# Initialize object to store comment_id of previous comment in second query
lastcom2 = 'abcdefg'

In [47]:
# Iterate through comments and replies of second query, analyze for hatefulness, then place scores in the table
# NOTE: this may take several minutes to complete
for index,row in comreps2.iterrows():
  if(row['comment_id'] != lastcom2):
    h_com = hate.predict(row['text_com'])
    comreps2.at[index, 'hate_com'] = h_com.probas['hateful']
    lastcom2 = row['comment_id']
  else:
    comreps2.at[index, 'hate_com'] = h_com.probas['hateful']
  h_rep = hate.predict(row['text_rep'])
  comreps2.at[index, 'hate_rep'] = h_rep.probas['hateful']
  if((index + 1) % 50 == 0):
    print(index + 1,end=" ")

50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950 1000 1050 1100 1150 1200 1250 1300 1350 1400 1450 1500 1550

In [48]:
# Print comments, replies, and hatefulness probabilities for second query
comreps2

,video_id_com,comment_id,comment_like_count_com,text_com,video_id_rep,comment_parent_id,comment_like_count_rep,text_rep,hate_com,hate_rep
0,6bN_YI-3phA,UgytCUKu28TxwJZpw814AaABAg,0,"Notice he calls him the right name though, Tru...",None,UgytCUKu28TxwJZpw814AaABAg,0,Cope.,0.01503,0.030553
1,6bN_YI-3phA,UgxipKY4ytIoEDaZ8Uh4AaABAg,2,Biden did not call him Obama he just think thi...,None,UgxipKY4ytIoEDaZ8Uh4AaABAg,1,He called him Barack three times!,0.017419,0.017207
2,6bN_YI-3phA,UgxugNbc6vWX2WQX1DN4AaABAg,1,This is embarrassing and definitely should be ...,None,UgxugNbc6vWX2WQX1DN4AaABAg,0,Have you listened to Donny lately . Trump does...,0.017799,0.014629
3,6bN_YI-3phA,UgxugNbc6vWX2WQX1DN4AaABAg,1,This is embarrassing and definitely should be ...,None,UgxugNbc6vWX2WQX1DN4AaABAg,0,For what campaign? the guy isn’t running again...,0.017799,0.028423
4,6bN_YI-3phA,UgxV9l1daF3CISA32rt4AaABAg,5,That's as funny as a Bible salesman not knowin...,None,UgxV9l1daF3CISA32rt4AaABAg,0,Cause that bible salesman is a narcissist a li...,0.020096,0.264925
...,...,...,...,...,...,...,...,...,...,...
1556,ZVvvDKsUyXk,UgwZj-LWi3Qdk0guEfV4AaABAg,26,"RIP Joe Biden, I mean Jeese Jackson.",None,UgwZj-LWi3Qdk0guEfV4AaABAg,2,The joke was about how Joe was making it about...,0.015554,0.013653
1557,ZVvvDKsUyXk,UgwZj-LWi3Qdk0guEfV4AaABAg,26,"RIP Joe Biden, I mean Jeese Jackson.",None,UgwZj-LWi3Qdk0guEfV4AaABAg,0,"@Ale....\nI am not the only one, who found the...",0.015554,0.015038
1558,ZVvvDKsUyXk,Ugx5NzD8k62-XV5lb-d4AaABAg,26,Miss you Joe,None,Ugx5NzD8k62-XV5lb-d4AaABAg,5,Even if he doesn't even know where he is at! 😂,0.018636,0.014321
1559,ZVvvDKsUyXk,Ugx5NzD8k62-XV5lb-d4AaABAg,26,Miss you Joe,None,Ugx5NzD8k62-XV5lb-d4AaABAg,3,"He was awful too just like trump, both raising...",0.018636,0.01951
1560,ZVvvDKsUyXk,Ugx5NzD8k62-XV5lb-d4AaABAg,26,Miss you Joe,None,Ugx5NzD8k62-XV5lb-d4AaABAg,0,Rip,0.018636,0.038022

### 4. Compare the two sets in how hate in comments *(descriptive norm)* is associated with hate in replies

In [49]:
# Create columns to store indicator for first/second query
comreps1['query'] = 0
comreps2['query'] = 1

In [50]:
# Append the two tables together
all = pd.concat([comreps1,comreps2],ignore_index = True)

In [51]:
# Print table of comments
all

,video_id_com,comment_id,comment_like_count_com,text_com,video_id_rep,comment_parent_id,comment_like_count_rep,text_rep,hate_com,hate_rep,query
0,_7dMrX-YY34,Ugzwy62qcq4su1TAyQx4AaABAg,1,And his fools believe it,None,Ugzwy62qcq4su1TAyQx4AaABAg,0,No actually trump is making 14 billion dollars...,0.029216,0.017533,0
1,_7dMrX-YY34,Ugzwy62qcq4su1TAyQx4AaABAg,1,And his fools believe it,None,Ugzwy62qcq4su1TAyQx4AaABAg,0,​@repulse_wkey4432 follow the money,0.029216,0.020233,0
2,nZOxZKDAJH0,UgwbijTvkEdcVSuDFip4AaABAg,2,"Dos frases que para ser felices,hay que elimin...",None,UgwbijTvkEdcVSuDFip4AaABAg,0,Palabras de sabios.,0.015486,0.018797,0
3,nZOxZKDAJH0,Ugx4kyn5yHhMbhgtyFJ4AaABAg,0,Osea Trump quiere q el papá le aplauda sus est...,None,Ugx4kyn5yHhMbhgtyFJ4AaABAg,0,"La paz viene de Cristo , y el mundo reclama p...",0.015134,0.015824,0
4,nZOxZKDAJH0,UgxefcfPgnsU0EtZDn14AaABAg,0,"Creeré en el Papa, cuando como Jesucristo, se ...",None,UgxefcfPgnsU0EtZDn14AaABAg,0,Cree en Cristo atravez del Papa el papá es un...,0.016532,0.015374,0
...,...,...,...,...,...,...,...,...,...,...,...
1881,ZVvvDKsUyXk,UgwZj-LWi3Qdk0guEfV4AaABAg,26,"RIP Joe Biden, I mean Jeese Jackson.",None,UgwZj-LWi3Qdk0guEfV4AaABAg,2,The joke was about how Joe was making it about...,0.015554,0.013653,1
1882,ZVvvDKsUyXk,UgwZj-LWi3Qdk0guEfV4AaABAg,26,"RIP Joe Biden, I mean Jeese Jackson.",None,UgwZj-LWi3Qdk0guEfV4AaABAg,0,"@Ale....\nI am not the only one, who found the...",0.015554,0.015038,1
1883,ZVvvDKsUyXk,Ugx5NzD8k62-XV5lb-d4AaABAg,26,Miss you Joe,None,Ugx5NzD8k62-XV5lb-d4AaABAg,5,Even if he doesn't even know where he is at! 😂,0.018636,0.014321,1
1884,ZVvvDKsUyXk,Ugx5NzD8k62-XV5lb-d4AaABAg,26,Miss you Joe,None,Ugx5NzD8k62-XV5lb-d4AaABAg,3,"He was awful too just like trump, both raising...",0.018636,0.01951,1
1885,ZVvvDKsUyXk,Ugx5NzD8k62-XV5lb-d4AaABAg,26,Miss you Joe,None,Ugx5NzD8k62-XV5lb-d4AaABAg,0,Rip,0.018636,0.038022,1

In [52]:
# Print variable types
all.dtypes

video_id_com              object
comment_id                object
comment_like_count_com    object
text_com                  object
video_id_rep              object
comment_parent_id         object
comment_like_count_rep    object
text_rep                  object
hate_com                  object
hate_rep                  object
query                      int64
dtype: object

In [53]:
# Convert variable types to numbers
all['comment_like_count_com'] = all['comment_like_count_com'].astype(int)
all['hate_com'] = all['hate_com'].astype(float)
all['comment_like_count_rep'] = all['comment_like_count_rep'].astype(int)
all['hate_rep'] = all['hate_rep'].astype(float)

In [54]:
# Print variable types after changes
all.dtypes

video_id_com               object
comment_id                 object
comment_like_count_com      int64
text_com                   object
video_id_rep               object
comment_parent_id          object
comment_like_count_rep      int64
text_rep                   object
hate_com                  float64
hate_rep                  float64
query                       int64
dtype: object

In [55]:
# Create binary variables capturing if probability of hatefulness in comments and replies > 50%
all['hate_thresh_com'] = all['hate_com'].apply(lambda x: 1 if x > .5 else 0)
all['hate_thresh_rep'] = all['hate_rep'].apply(lambda x: 1 if x > .5 else 0)

In [56]:
# Print number of comment-reply pairs where comment has probability of hatefulness > 50%
all.loc[all['hate_thresh_com'] == 1].size

871

In [57]:
# Print number of comment-reply pairs where reply has probability of hatefulness > 50%
all.loc[all['hate_thresh_rep'] == 1].size

975

In [58]:
# Create column of all 1s to add a constant to the models
all['constant'] = 1

In [59]:
# Model how comment hate probability is associated with reply hate probability using OLS regression
model1 = sm.OLS(all['hate_rep'],all[['hate_com','constant']])

In [60]:
# Print Model 1 results
model1.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               hate_rep   R-squared:                       0.020
Model:                            OLS   Adj. R-squared:                  0.019
Method:                 Least Squares   F-statistic:                     38.01
Date:                Thu, 16 Apr 2026   Prob (F-statistic):           8.59e-10
Time:                        17:05:30   Log-Likelihood:                 850.88
No. Observations:                1886   AIC:                            -1698.
Df Residuals:                    1884   BIC:                            -1687.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
hate_com       0.1435      0.023      6.165      0.000       0.098       0.189
constant       0.0563      0.004     14.489      0.000       0.049       0.064
==============================================================================
Omnibus:                     1572.531   Durbin-Watson:                   1.848
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            27006.010
Skew:                           4.064   Prob(JB):                         0.00
Kurtosis:                      19.662   Cond. No.                         6.59
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [61]:
# Model how comment hate prevalence is associated with reply hate prevalence using OLS regression
model2 = sm.OLS(all['hate_thresh_rep'],all[['hate_thresh_com','constant']])

In [62]:
# Print Model 2 results
model2.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:        hate_thresh_rep   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                  0.006
Method:                 Least Squares   F-statistic:                     11.60
Date:                Thu, 16 Apr 2026   Prob (F-statistic):           0.000675
Time:                        17:05:34   Log-Likelihood:                 408.85
No. Observations:                1886   AIC:                            -813.7
Df Residuals:                    1884   BIC:                            -802.6
Df Model:                           1
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
hate_thresh_com     0.0826      0.024      3.405      0.001       0.035       0.130
constant            0.0368      0.005      8.060      0.000       0.028       0.046
==============================================================================
Omnibus:                     1747.276   Durbin-Watson:                   1.913
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            38302.291
Skew:                           4.672   Prob(JB):                         0.00
Kurtosis:                      23.003   Cond. No.                         5.41
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [63]:
# Model how comment hate prevalence is associated with reply hate prevalence using Logit regression
model3 = sm.GLM(all['hate_thresh_rep'],all[['hate_thresh_com','constant']],family=sm.families.Binomial())

In [64]:
# Print Model 3 results
model3.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:        hate_thresh_rep   No. Observations:                 1886
Model:                            GLM   Df Residuals:                     1884
Model Family:                Binomial   Df Model:                            1
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -311.45
Date:                Thu, 16 Apr 2026   Deviance:                       622.89
Time:                        17:06:49   Pearson chi2:                 1.89e+03
No. Iterations:                     6   Pseudo R-squ. (CS):           0.004125
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
hate_thresh_com     1.2657      0.397      3.190      0.001       0.488       2.043
constant           -3.2638      0.124    -26.219      0.000      -3.508      -3.020
===================================================================================
"""

In [65]:
# Create columns capturing the interaction between query and hatefulness of comments
all['interaction'] = all['query']*all['hate_com']
all['int_thresh'] = all['query']*all['hate_thresh_com']

In [66]:
# Model how comment-reply hate probability association varies across the two queries using OLS regression
model4 = sm.OLS(all['hate_rep'],all[['hate_com','query','interaction','constant']])

In [ ]:
# Print Model 4 results
model4.fit().summary()

In [ ]:
# Model how comment-reply hate prevalence association varies across the two queries using Logit regression
model5 = sm.GLM(all['hate_thresh_rep'],all[['hate_thresh_com','query','int_thresh','constant']],family=sm.families.Binomial())

In [ ]:
# Print Model 5 results
model5.fit().summary()

### 5. Compare the two sets in how hate *(descriptive norm)* and like counts *(injunctive norm)* of comments <b>interact</b> in their association with hate in replies (i.e., Theory of Normative Social Behavior)

In [ ]:
# Create columns capturing the interaction between like counts and hatefulness of comments
all['tnsb'] = all['comment_like_count_com']*all['hate_com']
all['tnsb_thresh'] = all['comment_like_count_com']*all['hate_thresh_com']

In [ ]:
# Model how comment-reply hate probability association varies with like counts using OLS regression
model6 = sm.OLS(all['hate_rep'],all[['hate_com','comment_like_count_com','tnsb','constant']])

In [ ]:
# Print Model 6 results
model6.fit().summary()

In [ ]:
# Model how comment-reply hate prevalence association varies with like counts using Logit regression
model7 = sm.GLM(all['hate_thresh_rep'],all[['hate_thresh_com','comment_like_count_com','tnsb_thresh','constant']],family=sm.families.Binomial())

In [ ]:
# Print Model 7 results
model7.fit().summary()

In [ ]:
# Create column capturing the interaction between query and like counts of comments
all['q_like'] = all['comment_like_count_com']*all['query']

In [ ]:
# Create columns capturing the TRIPLE interaction between query, like counts, and hatefulness of comments
all['tnsb_int'] = all['comment_like_count_com']*all['hate_com']*all['query']
all['tnsb_int_thresh'] = all['comment_like_count_com']*all['hate_thresh_com']*all['query']

In [ ]:
# Model how comment-reply hate probability association varies with like counts AND query using OLS regression
model8 = sm.OLS(all['hate_rep'],all[['hate_com','comment_like_count_com','query','tnsb','interaction','q_like','tnsb_int','constant']])

In [ ]:
# Print Model 8 results
model8.fit().summary()

In [ ]:
# Model how comment-reply hate prevalence association varies with like counts AND query using Logit regression
model9 = sm.GLM(all['hate_thresh_rep'],all[['hate_thresh_com','comment_like_count_com','query','tnsb_thresh','int_thresh','q_like','tnsb_int_thresh','constant']],family=sm.families.Binomial())

In [ ]:
# Print Model 9 results
model9.fit().summary()

#### <u>Additional considerations</u>
1.   Comment like counts are skewed --> could transform with logarithm
2.   Arbitrary threshold of .5 for hate --> higher numbers (e.g., .6, .9) are sometimes used<br> --> likely need more data
3.   Add fixed/random effects for video, comment, and/or authors<br>--> likely need more data